project_id = "zjedwybadmqdcglhflbs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://app.renovirt.de"
additional_redirect_urls = ["https://app.renovirt.de", "http://localhost:3000", "https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false

[db]
port = 54323

[db.pooler]
enabled = false
port = 54327
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54324
ip_version = "ipv6"

[studio]
enabled = true
port = 54325
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54326
smtp_port = 54327
pop3_port = 54328

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[edge_runtime]
enabled = true
port = 54329
inspector_port = 5050

[functions.ai-help-assistant]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.resend-verification-email]
verify_jwt = false

[functions.send-chat-history]
verify_jwt = true

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-admin-order-notification]
verify_jwt = false

[functions.send-email-change-request]
verify_jwt = true

[functions.send-test-email]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false