// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjedwybadmqdcglhflbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZWR3eWJhZG1xZGNnbGhmbGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjgzODgsImV4cCI6MjA2Mzg0NDM4OH0.qVCxgW4oJrtLKHHYdqlr0eXY64tjd0UH7XRbr2zCkyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);